# $FreeBSD: www/en/advocacy/Makefile,v 1.3 2002/04/05 05:37:35 kuriyama Exp $
#
# Makefile for the advocacy site

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   index.sgml
DOCS+=	myths.sgml
DOCS+=	letter.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
