# $FreeBSD: www/en/releases/5.2R/Makefile,v 1.2 2003/10/31 00:54:05 scottl Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	todo.sgml schedule.sgml

DATA=	docbook.css

.include "${WEB_PREFIX}/share/mk/web.site.mk"
