# The FreeBSD Documentation Project
# The FreeBSD Brazilian Portuguese Documentation Project
#
# Original revision: 1.7
#
# $FreeBSD: doc/pt_BR.ISO8859-1/Makefile,v 1.1 2002/01/28 19:36:44 lioux Exp $

SUBDIR+= books

COMPAT_SYMLINK = pt_BR
COMPAT_SYMLINK += br

DOC_PREFIX?= ${.CURDIR}/..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
