# $FreeBSD: www/en/smp/Makefile,v 1.2 2000/11/07 04:05:37 kuriyama Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   index.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
