# $FreeBSD: /repoman/r/dcvs/doc/en_US.ISO8859-1/articles/hubs/Makefile,v 1.4 2003/04/22 18:35:38 hrs Exp $

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

WITH_ARTICLE_TOC?=YES

SRCS= article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
