# $FreeBSD: doc/en_US.ISO8859-1/articles/diskless-x/Makefile,v 1.7 2003/04/22 18:35:37 hrs Exp $

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS= article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
