# $FreeBSD: www/en/handbook/Makefile,v 1.9 2002/06/27 19:55:40 nik Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=   index.html 

.include "${WEB_PREFIX}/share/mk/web.site.mk"
