# $FreeBSD: www/en/news/1996/Makefile,v 1.3 2000/11/07 04:05:19 kuriyama Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	index.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
