# $FreeBSD: www/en/events/2002/Makefile,v 1.2 2002/08/16 07:30:40 murray Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS?=	bsdcon-devsummit.sgml usenix-devsummit.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
