# The FreeBSD Documentation Project
# The FreeBSD Brazilian Portuguese Documentation Project
# 
# Original revision: 1.4
#
# $FreeBSD: doc/pt_BR.ISO8859-1/books/Makefile.inc,v 1.1 2002/01/28 19:53:42 lioux Exp $

DESTDIR?=	${DOCDIR}/pt_BR.ISO8859-1/books/${.CURDIR:T}
