# The FreeBSD Documentation Project
# The FreeBSD Brazilian Portuguese Documentation Project
#
# Original revision: 1.10
#
# $FreeBSD: doc/pt_BR.ISO8859-1/books/Makefile,v 1.1 2002/01/28 19:52:42 lioux Exp $

#SUBDIR = corp-net-guide
#SUBDIR+= design-44bsd
#SUBDIR+= developers-handbook
SUBDIR+= faq
#SUBDIR+= fdp-primer
SUBDIR+= handbook
#SUBDIR+= porters-handbook
#SUBDIR+= ppp-primer

ROOT_SYMLINKS= handbook

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
