# $FreeBSD: www/en/news/1993/Makefile,v 1.1 2003/05/21 07:56:25 murray Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	freebsd-coined.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
