# $FreeBSD: www/en/events/2003/Makefile,v 1.1 2003/09/22 07:41:56 murray Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS?=	bsdcon-devsummit.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
