#
# $FreeBSD: doc/en_US.ISO8859-1/articles/laptop/Makefile,v 1.3 2003/04/22 18:35:39 hrs Exp $
#
# Article about using FreeBSD on laptops
#

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS= article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
