# $FreeBSD: www/en/releases/1.1.5/Makefile,v 1.2 2000/11/07 04:05:22 kuriyama Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=	CONTRIB.386BSD CONTRIB.FreeBSD COPYRIGHT.386BSD
DATA+=	COPYRIGHT.FreeBSD COPYRIGHT.USL KNOWNBUGS MIRROR.SITES
DATA+=	PERSONAL.ACKS REGISTER.FreeBSD RELNOTES.FreeBSD ROSTER.FreeBSD
DATA+=	SUPPORT.TXT TODO-1.1.5

.include "${WEB_PREFIX}/share/mk/web.site.mk"
