# $FreeBSD: www/en/ports/growth/Makefile,v 1.2 2002/05/20 13:49:27 phantom Exp $
#

TOOLDIR=${.CURDIR}/../../../tools/portsgrowth

all install clean:
	cd ${TOOLDIR}; \
		 ${MAKE} ${MAKEFLAGS} ${.TARGETS}

