# Summary for C99 project status
#
# $FreeBSD: www/en/projects/mips/Makefile,v 1.1 2002/11/08 14:56:50 jmallett Exp $

MAINTAINER=	jmallett

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	index.sgml
DATA=	style.css

.include "${WEB_PREFIX}/share/mk/web.site.mk"
