# $FreeBSD: www/en/kse/Makefile,v 1.1 2002/11/04 00:18:27 mini Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   index.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
