# $FreeBSD: www/en/ports/Makefile.inc0,v 1.4 2000/11/07 08:31:00 kuriyama Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif
.if exists(Makefile.inc)
.include "Makefile.inc"
.endif

.if exists(Makefile.gen)
.include "Makefile.gen"
.endif

.include "${WEB_PREFIX}/share/mk/web.site.mk"
