# $FreeBSD: www/en/news/1998/Makefile,v 1.2 2001/10/29 10:14:32 murray Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	index.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
